<?php

namespace CL\BlogBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
	public function getAdverts()
	{
		$query = $this->createQueryBuilder('a')
		//Jointure sur notre attribut Image
		->leftJoin('a.image','i')
		->addSelect('i')
		->orderBy('a.date','DESC')
		->getQuery()
	;
	
	return $query->getResult();
	}
}
